spring.application.name=myportfolio

# ===========================
# Server Configuration
# ===========================
server.port=${PORT:8080}

# ===========================
# Datasource Configuration
# ===========================

#spring.datasource.url=jdbc:postgresql://localhost:5432/my_portfolio
#spring.datasource.username=postgres
#spring.datasource.password=12345


#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
#spring.datasource.username=postgres.djbgozqfffkavmavmwwf
#spring.datasource.password=Rifat12330@

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate Configuration
# ===========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# Logging
# ===========================

logging.level.org.springframework=INFO
logging.level.com.yourplayground=DEBUG

# ===========================
# Spring Profiles
# ===========================
spring.profiles.active=default

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

